name: Bundle Binaries

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5

      - name: Dotnet Publish
        run: dotnet publish

      - name: Artifact Bundle
        id: bundle
        run: |
          [XML]$xml = Get-Content .\XmlFormatter.CommandLine\XmlFormatter.CommandLine.csproj
          $version = $xml.Project.PropertyGroup.Version
          $targetFramework = $xml.Project.PropertyGroup.TargetFramework
          $zipFile = "XmlFormatter.CommandLine_v$version"
          $artifactPath = ".\XmlFormatter.CommandLine\bin\Release\$targetFramework\publish\*"
          "ZIP_FILENAME=$zipFile" >> $env:GITHUB_OUTPUT
          "ARTIFACT_PATH=$artifactPath" >> $env:GITHUB_OUTPUT

      - name: Upload Artifact
        uses: actions/upload-artifact@v6
        with:
          name: ${{ steps.bundle.outputs.ZIP_FILENAME }}
          path: ${{ steps.bundle.outputs.ARTIFACT_PATH }}

      - name: Github Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: ${{ steps.bundle.outputs.ARTIFACT_PATH }}
